/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javagroup70;


import OOPJ.Classes.User;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


/**
 *
 * @author mrykk
 */
public class StudentUpdate extends javax.swing.JFrame {

    /**
     * Creates new form StudentUpdate
     */
    public StudentUpdate() {
        initComponents();
        User User = new User();
        
        String file = "user.txt";

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Process the line here
                String[] parts = line.split(",");
                if(User.getPassport().equals (parts[0])){
                    String ageStr = User.getAge();
                    int age = Integer.parseInt(ageStr);
                    txtPassport.setText(parts[0]);
                    txtFirst1.setText(parts[2]);
                    txtLast.setText(parts[3]);
                    txtPassword.setText(parts[7]);
                    txtContact.setText(parts[8]);
                    cmbAge.setSelectedItem(parts[4]);
                    txtGender.setText(parts[5]);
                    txtPassport.setEditable(false);
                    txtFirst1.setEditable(false);
                    txtLast.setEditable(false);
                    txtGender.setEditable(false);
                }
                
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUpdate = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblLast = new javax.swing.JLabel();
        lblPassport = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtLast = new javax.swing.JTextField();
        txtPassport = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        cmbAge = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblFirst1 = new javax.swing.JLabel();
        txtFirst1 = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUpdate.setText("Update Profile");
        jPanel1.add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 16, -1, -1));

        lblPassword.setText("Password: ");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, 20));

        lblLast.setText("Last Name:");
        jPanel1.add(lblLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        lblPassport.setText("ID/Passport:");
        jPanel1.add(lblPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 143, -1, -1));

        lblGender.setText("Gender:");
        jPanel1.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        lblAge.setText("Age: ");
        jPanel1.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        lblContact.setText("Contact No:");
        jPanel1.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 71, -1));

        txtLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastActionPerformed(evt);
            }
        });
        jPanel1.add(txtLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 71, -1));
        jPanel1.add(txtPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 71, -1));
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 112, -1));

        cmbAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66+" }));
        jPanel1.add(cmbAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 300, 90, 30));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 30));

        lblFirst1.setText("First Name:");
        jPanel1.add(lblFirst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        txtFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirst1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtFirst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 71, -1));
        jPanel1.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String contact = txtContact.getText();
        String age = (String) cmbAge.getSelectedItem();
        String pass = txtPassword.getText();
        String passp = txtPassport.getText();
        
        User User = new User();
        User.updateProfile(passp, contact, age, pass);
        
        
        
       
       
       
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        switch (User.getRole()){
            case "Admin":
                new AdminHome().setVisible(true);
                this.dispose();
                break;
            case "Student":
                new StudentHome().setVisible(true);
                this.dispose();
                break;
        }
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirst1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirst1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbAge;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblFirst1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLast;
    private javax.swing.JLabel lblPassport;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtFirst1;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtPassport;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
